### ISSUE TITLE
Upgrade antd to latest version

### ISSUE THREAD

**Issue by chilijung** [Canner/antd-canner-components#36]
https://github.com/Canner/antd-canner-components/blob/canary/package.json#L73

Since in latest version of antd 3.9.x the icons works differently instead of loading icons from CDN. And many others, since we are using the latest version in cms-page which antd related projects should also update in order to prevent unexpected breaks.

https://ant.design/changelog#3.9.3

**Comment by abz53378** [comment]
Fix in b4b1d3d5dc33beca349a6427861c1cc5b1427976
